url: https://dcleres.github.io
baseurl: /investing_for_social_good

# Site settings
title: Project Social Good - EPFL - ADA
email: david.cleres@epfl.ch
description: "Society is demanding that companies, both public and private, serve a social purpose. To prosper over time,
every company must not only deliver financial performance but also show how it makes a positive contribution to society. \n
- Laurence D. Fink, CEO BlackRock"

google_analytics: UA-129985136-3
htmlwidgets: TRUE


# Team names, titles and social links
people:
- name: David Cleres
  pic: DC
  position: Computationnal Science & Engineering (CSE)
  social:
    - title: twitter
      url: https://twitter.com/DavidCleres
    - title: facebook
      url: https://www.facebook.com/david.cleres
    - title: stack-overflow
      url: https://stackoverflow.com/users/9543860/dcleres

- name: Mike Jiao
  pic: 2
  position: Computer Science (CS)
  social:
    - title: twitter
      url: https://twitter.com/mikejiao212
    - title: facebook
      url: https://www.facebook.com/mike.jiao.5
    - title: linkedin
      url: https://www.linkedin.com/in/mikejiao/

- name: Nicolas Lesimple
  pic: 3
  position: Computationnal Science & Engineering (CSE)
  social:
    - title: twitter
      url: https://twitter.com/NicolasLesimple
    - title: facebook
      url: https://www.facebook.com/nicolas.lesimple
    - title: linkedin
      url: https://www.linkedin.com/in/nicolas-lesimple-219014127/

# Postal address (add as many lines as necessary)
address:
  - line: EPFL
  - line: Lausanne

# Build settings
markdown: kramdown
permalink: pretty
